# Generated by Django 4.0 on 2022-01-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='authentificateUser',
        ),
    ]
