# Generated by Django 4.0 on 2021-12-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20211214_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='entrance',
            new_name='graphic',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='house',
            new_name='interior',
        ),
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=256),
        ),
    ]
