# Generated by Django 4.0 on 2022-01-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('start_work', models.DateField()),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.unit')),
                ('position', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.position')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('start_work', models.DateField()),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.unit')),
                ('position', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.position')),
            ],
        ),
    ]
